name: Push to Main

on:
  push:
    branches:
      - main # Only trigger on development branch pushes
  workflow_dispatch: # Allow manual triggering of workflow

jobs:
  pact-tests:
    name: Pact Contract Tests
    runs-on: ubuntu-latest
    needs: [setup, build]
    if: ${{ vars.RUN_CONTRACT_TESTS == 'true' }} # Only runs if enabled via GitHub Actions variable

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'tsconfig.tsbuildinfo'

      - name: Run Pact Contract Tests
        run: CONTRACT_TEST_COMMAND # Define a contract test command
